version: '3'
services:
  # nacos-server服务注册与发现，配置中心服务
  nacos1:
    platform: linux/x86_64
    hostname: nacos1
    container_name: nacos1
    image: zill057/nacos-server-apple-silicon:2.0.3
    volumes:
      - ../dockerFileData/nacos/cluster-logs/nacos1:/home/nacos/logs #日志输出目录
    ports:
      - "8848:8848"
      - "9555:9555"
    env_file:
       - ./env/nacos-hostname.env #配置文件
    privileged: true
    restart: always
    networks:
      default:
        ipv4_address: 172.23.0.17

  # nacos2:
  #   hostname: nacos2
  #   container_name: nacos2
  #   image: nacos/nacos-server:latest
  #   volumes:
  #     - ./cluster-logs/nacos2:/home/nacos/logs #日志输出目录
  #   ports:
  #     - "8849:8848"
  #   env_file:
  #      - ./env/nacos-hostname.env #配置文件
  #   privileged: true
  #   restart: always
  #   networks:
  #     default:
  #       ipv4_address: 172.23.0.17

  # nacos3:
  #   hostname: nacos3
  #   container_name: nacos3
  #   image: nacos/nacos-server:latest
  #   volumes:
  #     - ./cluster-logs/nacos3:/home/nacos/logs #日志输出目录
  #   ports:
  #     - "8850:8848"
  #   env_file:
  #      - ./env/nacos-hostname.env #配置文件
  #   privileged: true
  #   restart: always
  #   networks:
  #     default:
  #       ipv4_address: 172.23.0.18

networks:
  default:
    external:
      name: tang_network
