version: '3'
services:
  mysql:
    platform: linux/x86_64
    image: mysql:5.7
    restart: always
    container_name: mysql01
    environment:
      MYSQL_ROOT_PASSWORD: "6200152"
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
      --max_allowed_packet=128M;
    ports:
      - 3307:3306
    volumes:
     - ./mysql01/data:/var/lib/mysql
     - ./mysql01/conf:/etc/mysql/mysql.conf.d
    networks:
      default:
        ipv4_address: 172.23.0.15
networks:
  default:
    external:
      name: zookeeper_network
